# https://yazi-rs.github.io/docs/configuration/keymap
# https://yazi-rs.github.io/docs/tips/
[manager]
# --block stops yazi UI until done

# setbg to what cursor is on
prepend_keymap = [
	{ on = "b", run = 'shell "wallscheme $0" --confirm', desc = "Just for test!" },
]
